
import React from 'react';
import { AlertTriangle } from 'lucide-react';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';

const Disclaimer: React.FC = () => {
  return (
    <section id="disclaimer" className="py-16 md:py-24 bg-charcoal/30">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl md:text-4xl font-bold text-center text-glow mb-6">
          Legal Disclaimer
        </h2>
        
        <div className="max-w-4xl mx-auto">
          <Alert className="mb-6 cyberpunk-card">
            <AlertTriangle className="h-5 w-5 text-primary-purple" />
            <AlertTitle>Important Notice</AlertTitle>
            <AlertDescription className="text-light-gray/80">
              This service is provided for informational, educational, and research purposes only. Please read the following disclaimer carefully before using the Native American History Time Machine of Destiny.
            </AlertDescription>
          </Alert>
          
          <div className="space-y-6 text-light-gray/80">
            <p>
              The Native American History Time Machine of Destiny (referred to as "the Service") is an AI-powered educational and entertainment tool designed to provide immersive storytelling experiences related to Native American history and culture.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Historical Content</h3>
            <p>
              While we strive for historical accuracy, the Service provides content for educational and entertainment purposes only. Users should consult academic and cultural sources for comprehensive historical research. The Service makes reasonable efforts to present historically accurate information, but we do not guarantee the complete accuracy of all details presented.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Cultural Representation</h3>
            <p>
              The Service aims to present Native American cultures with respect and authenticity. However, it is important to acknowledge that no AI system can fully capture the depth, complexity, and nuance of indigenous cultures and their histories. We encourage users to engage directly with Native American communities, cultural centers, and academic resources for more comprehensive understanding.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Future Scenarios</h3>
            <p>
              Any content related to potential future scenarios is entirely speculative and presented for entertainment and educational purposes only. These scenarios do not constitute predictions, forecasts, or advice regarding future events. The "Test of Two Sacred Fates" feature is a fictional narrative device designed to encourage critical thinking about the potential consequences of present-day decisions.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Image Generation</h3>
            <p>
              Images generated by the Service are AI-created approximations of historical and cultural content. These images are intended to enhance the storytelling experience and should not be considered historically accurate reproductions or documentary evidence.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">Limitation of Liability</h3>
            <p>
              AiWebTools.Ai and its affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary damages resulting from your use of the Service or any content provided therein. By using the Service, you agree to indemnify and hold harmless AiWebTools.Ai and its affiliates from any claims arising from your use of the Service.
            </p>
            
            <h3 className="text-xl font-semibold text-primary-purple">User Responsibility</h3>
            <p>
              Users are responsible for their use of the Service and should exercise critical thinking when consuming any historical or cultural content. The Service is not a substitute for professional research or consultation with cultural experts.
            </p>
            
            <p className="font-semibold">
              By using the Native American History Time Machine of Destiny, you acknowledge that you have read, understood, and agree to be bound by this disclaimer.
            </p>
            
            <div className="mt-8 p-4 bg-primary-purple/10 rounded-lg border border-primary-purple/20">
              <p className="text-center text-light-gray/80 font-medium">
                For informational, educational, and research purposes only.
              </p>
              
              {/* Signature */}
              <div className="mt-8 text-right">
                <p className="text-primary-purple/80 text-2xl font-cursive italic opacity-90">
                  Sincerely, Pahana
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Disclaimer;
